<a href="https://colab.research.google.com/github/data-science-and-machine-learning/gradient-descent/blob/master/06_Implement_SGD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.datasets import load_boston
from random import seed
from random import randrange
from csv import reader
from math import sqrt
from sklearn import preprocessing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from prettytable import PrettyTable
from sklearn.linear_model import SGDRegressor
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error

In [0]:
X = load_boston().data
Y = load_boston().target

In [0]:
scaler = preprocessing.StandardScaler().fit(X)
X = scaler.transform(X)

In [4]:
clf = SGDRegressor()
clf.fit(X, Y)
print(mean_squared_error(Y, clf.predict(X)))

22.029561236553864

In [13]:
import matplotlib.pyplot as plt
load_boston().feature_names
df= pd.DataFrame(data= X)
df['Target']= Y
df.head(15)

#plt.plot(df['Target'])

           0         1         2  ...        11        12  Target
0  -0.419782  0.284830 -1.287909  ...  0.441052 -1.075562    24.0
1  -0.417339 -0.487722 -0.593381  ...  0.441052 -0.492439    21.6
2  -0.417342 -0.487722 -0.593381  ...  0.396427 -1.208727    34.7
3  -0.416750 -0.487722 -1.306878  ...  0.416163 -1.361517    33.4
4  -0.412482 -0.487722 -1.306878  ...  0.441052 -1.026501    36.2
5  -0.417044 -0.487722 -1.306878  ...  0.410571 -1.043322    28.7
6  -0.410243  0.048772 -0.476654  ...  0.426798 -0.031268    22.9
7  -0.403696  0.048772 -0.476654  ...  0.441052  0.910700    27.1
8  -0.395935  0.048772 -0.476654  ...  0.328448  2.421774    16.5
9  -0.400729  0.048772 -0.476654  ...  0.329325  0.623344    18.9
10 -0.394346  0.048772 -0.476654  ...  0.393028  1.092926    15.0
11 -0.406847  0.048772 -0.476654  ...  0.441052  0.086478    18.9
12 -0.409604  0.048772 -0.476654  ...  0.370880  0.428502    21.7
13 -0.347230 -0.487722 -0.437258  ...  0.441052 -0.615792    20.4
14 -0.346276 -0.487722 -0.437258  ...  0.255974 -0.335445    18.2

[15 rows x 14 columns]

In [12]:
# number of dimentions: 
print('Model will be a {} dimentional plane'.format(len(df.columns)))

Model will be a 14 dimentional plane

In [75]:
# Steps for gradient descent:
#1. iterate through all datapoints
#2. Apply equation of gradient descent
#3. return the equation of the hyperplane


# predicted = ax0 + bx1 + cx2 + dx3 + ex4 + fx5 + gx6 + hx7 + ix8 + jx9 + kx10 + lx11+ mx12+ n

# loss = Target - predicted



#a = a + loss * x0 * learning rate
#same goes for all slopes b, c, d... m

#for the intercept: 
#n = n + loss * learning rate

def gradientDescent(dataframe, learning_rate):
  slopes= np.repeat(1, (dataframe.shape[1]-1))
  print('slopes= ', slopes,  end=' | \n')
  intercept= 0
 
  for each in dataframe:
    point= np.array(dataframe.iloc[each]) 
    x= point[:-1]
    y= point[-1:]
    
    # predicted value=  ax0 + bx1 + cx2 + dx3 + ex4 + fx5 + gx6 + hx7 + ix8 + jx9 + kx10 + lx11+ mx12+ intercept
    predicted= np.sum(slopes * x)+intercept
    error= y[0]- predicted
    for i in range(len(slopes)):
      #print(slopes[i], x[i])
      slopes[i] = slopes[i] + (error * x[i] * learning_rate)     
    
    intercept = intercept + (error * learning_rate)
    
    print('x=', x, end=' | ')
    print('y=', y[0], end=' | ')
    print('slopes= ', slopes,  end=' | ')
    print('intercept=', intercept, end=' | \n')
    break
  return slopes, intercept
    
slo, interc= gradientDescent(df, 0.1)
print(slo, ' | ', interc)

slopes=  [1 1 1 1 1 1 1 1 1 1 1 1 1] |
x= [-0.41978194  0.28482986 -1.2879095  -0.27259857 -0.14421743  0.41367189
 -0.12001342  0.1402136  -0.98284286 -0.66660821 -1.45900038  0.44105193
 -1.0755623 ] | y= 24.0 | slopes=  [ 0  1 -2  0  0  2  0  1 -1  0 -3  2 -2] | intercept= 2.9148767317690636 |
[ 0  1 -2  0  0  2  0  1 -1  0 -3  2 -2]  |  2.9148767317690636